[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "crisp-nam"
version = "0.1.0"
description = "CRISP-NAM: Competing Risks Interpretable Survival Prediction with Neural Additive Models"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "configargparse>=1.7",
    "lifelines>=0.30.0",
    "matplotlib>=3.10.1",
    "mypy>=1.19.1",
    "openpyxl>=3.1.5",
    "optuna>=4.3.0",
    "pandas>=2.2.3",
    "pyyaml>=6.0.2",
    "scikit-learn>=1.6.1",
    "scikit-survival>=0.24.1",
    "tabulate>=0.9.0",
    "torch>=2.7.0",
]

[dependency-groups]
docs = [
    "mkdocs>=1.5.3",
    "mkdocs-material>=9.5.12",
    "mkdocstrings>=0.24.1",
    "mkdocstrings-python>=1.8.0",
    "pymdown-extensions>=10.7.1",
    "mike>=2.0.0",
    "click<=8.2.1",
]

[project.urls]
Homepage = "https://github.com/VectorInstitute/crisp-nam"

[tool.mypy]
follow_imports = "normal"
ignore_missing_imports = false
install_types = true
pretty = true
non_interactive = true
allow_untyped_defs = false
no_implicit_optional = true
check_untyped_defs = true
namespace_packages = true
explicit_package_bases = true
warn_unused_configs = true
allow_subclassing_any = false
allow_untyped_calls = false
allow_incomplete_defs = false
allow_untyped_decorators = false
warn_redundant_casts = true
warn_unused_ignores = true
implicit_reexport = false
strict_equality = true
extra_checks = true
mypy_path = "crisp_nam"

[tool.ruff]
include = ["crisp_nam/*.py", "pyproject.toml", "*.ipynb"]
extend-exclude = ["*.csv", "*.json", "datasets/", "data_utils/", "training_scripts/"]
line-length = 88

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true

[tool.ruff.lint]
select = [
    "A", # flake8-builtins
    "B", # flake8-bugbear
    "COM", # flake8-commas
    "C4", # flake8-comprehensions
    "RET", # flake8-return
    "SIM", # flake8-simplify
    "ICN", # flake8-import-conventions
    "Q", # flake8-quotes
    "RSE", # flake8-raise
    "D", # pydocstyle
    "E", # pycodestyle
    "F", # pyflakes
    "I", # isort
    "W", # pycodestyle
    "N", # pep8-naming
    "ERA", # eradicate
    "PL", # pylint
]

fixable = ["A", "B", "COM", "C4", "RET", "SIM", "ICN", "Q", "RSE", "D", "E", "F", "I", "W", "N", "ERA", "PL"]
ignore = [
    "B905", # `zip()` without an explicit `strict=` parameter
    "E501", # line too long
    "D203", # 1 blank line required before class docstring
    "D213", # Multi-line docstring summary should start at the second line
    "PLR2004", # Replace magic number with named constant
    "PLR0913", # Too many arguments
    "COM812", # Missing trailing comma
    "ERA001", # Found commented-out code (too many false positives with math comments)
    "A001", # Ignore variable `input` is shadowing a Python builtin (common for torch)
    "A002", # Ignore variable `input` is shadowing a Python builtin in function (common for torch)
    "D301", # r-strings for docstrings with backslashes
]

# Ignore import violations in all `__init__.py` files.
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402", "F401", "F403", "F811"]

[tool.ruff.lint.pep8-naming]
ignore-names = ["X*", "setUp"]

[tool.ruff.lint.isort]
lines-after-imports = 2

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.pycodestyle]
max-doc-length = 88

[tool.hatch.build.targets.sdist]
only-include = ["crisp_nam"]