name: Build and Deploy documentation

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

permissions:
    contents: write
    pull-requests: write

jobs:
    build-blog:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                node-version: 'latest'
                cache: 'npm'
                cache-dependency-path: documentation/blog/package-lock.json
        
            - name: Install dependencies
              run: cd documentation/blog && npm ci
        
            - name: Build
              run: cd ./documentation/blog && npm run build
        
            - name: Upload blog build artifact
              uses: actions/upload-artifact@v6
              with:
                name: blog-build
                path: ./documentation/blog/public
                retention-days: 1

    build-docs:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6.0.1

            - name: Install uv
              uses: astral-sh/setup-uv@v7.2.0
              with:
                version: "0.9.11"
                enable-cache: true

            - name: Set up Python
              uses: actions/setup-python@v6.1.0
              with:
                python-version-file: ".python-version"

            - name: Install the project
              run: uv sync --all-extras --group docs

            - name: Build docs
              run: uv run mkdocs build

            - name: Create .nojekyll file
              run: touch site/.nojekyll

            - name: Upload docs site artifact
              uses: actions/upload-artifact@v6
              with:
                name: docs-site
                path: site/
                retention-days: 1


